baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Five Web Design"
theme = 'Hugo Profile'

[[Menus.main]]
identifier = "blog"
name = "Press"
title = "From our press"
url = "/blogs"
weight = 1

[params.navbar]
  disableSearch = true

[params]
  title = "5 Web Design"
  description = "Official website of 5 Web Design."
  animate = true
  favicon = "/5WD.png"

  [params.hero]
    enable = true
    intro = "Official website of"
    title = "Five Web Design"
    subtitle = "We build affordable websites with exceptional performance."
    image = "/5WD.png"
  
  [params.about]
    enable = true
    title = "About Us"
    content = "We help small businesses acheive their digital needs with the highest performance and the most affordable cost.\n"
    [params.about.skills]
      enable = true
      title = "Here are some of our services we offer: "
      items = ["Website Creation", "Website Hosting", "Mobile App Development", "Online Store Integration", "Custom Requests"]
    
  [params.experience]
    enable = true
    [[params.experience.items]]
    job = "Custom Website Developement"
    company = "Arete Enrichment Academy"
    companyUrl = "https://areteenrichmentacademy.org"
    date = "June 2024"
    content = "We made a custom tuition calculator that no web builder would ever provide."

    [params.experience.items.featuredLink]
      enable = true
      url = "https://tuition.pages.dev"
      name = "Check it out"

  [params.singlePages]
    socialShare = false

    [params.singlePages.readTime]
      enable = true
      content = "min read"
    [params.singlePages.scrollprogress]
      enable = true
    [params.singlePages.tags]
      openInNewTab = true